# reserved
RESERVED_USERNAME = "me"

# lengths
USERNAME_MAX_LENGTH = 150
EMAIL_MAX_LENGTH = 254
NAME_MAX_LENGTH = 256

# pagination
DEFAULT_PAGE_SIZE = 10
PAGINATION_PAGE_SIZE = DEFAULT_PAGE_SIZE

# review score
REVIEW_SCORE_MIN = 1
REVIEW_SCORE_MAX = 10
