# Generated by Django 5.1.1 on 2025-12-27 12:46

import django.core.validators
import django.db.models.deletion
import reviews.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genretitle",
            name="genre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="genre_titles",
                to="reviews.genre",
                verbose_name="Жанр",
            ),
        ),
        migrations.AlterField(
            model_name="genretitle",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="genre_titles",
                to="reviews.title",
                verbose_name="Произведение",
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="year",
            field=models.SmallIntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(
                        reviews.services.current_year
                    )
                ],
                verbose_name="Год выпуска",
            ),
        ),
    ]
